### ISSUE TITLE
Milestone 3 Feedback - Wilson/Rayce

### ISSUE THREAD

**Issue by RayceRossum** [UBC-MDS/DSCI_532_Mental-health-survey-Tech#12]
The product is good, the controls are clear and make sense for the type of data you want to filter. The use of tabbing is good to categorise the visuals.

Gender could add an "All" section. The plots are very difficult to interpret and compare between. The titles are very vague to the point where I'm not really sure what they're showing. 

Suggestions for improving the plots would be to use gridExtra to plot them on the same scale and switch to a column chart as opposed to a bar chart. Titles could be much more specific instead of just "comparison of *variable*" something like Care Options Utilisation Based on Availability. Addition of units to the axes would also improve clarity.

**Comment by sabrinatkk** [comment]
Thank you for your recommendation. @RayceRossum

Please review our [milestone 3 writeup](https://github.com/UBC-MDS/DSCI_532_Mental-health-survey-Tech/blob/master/doc/Milestone_3.md) and [app](https://panntingg.shinyapps.io/mental_health_app_3_0/) that has reflected on your suggestion.
