### ISSUE TITLE
Feedback from Linyang Yu, milestone 3

### ISSUE THREAD

**Issue by lyyu0413** [UBC-MDS/DSCI_532_Mental-health-survey-Tech#15]
Bad:
- Sidebar - Gender should have "all" to allow users to select all. Add description on the sidebar on how to interpret the graphs.
- Graphics - bars to be normalized. For thick bars (e.g. New Zealand), we should be consistent with the width of the bars so that every section has two bars.
- Font size
- Add description for each section in each tab, and make it consistent.

Good:
- the country filtering to show only countries with sufficient observations.
- tabs to show the areas of interest. This allows users to go deeper into the issues of mental health issues.
- bar charts to show parellel comparison between variables.

**Comment by sabrinatkk** [comment]
Thank you for your recommendation. 

Please review our [milestone 3 writeup](https://github.com/UBC-MDS/DSCI_532_Mental-health-survey-Tech/blob/master/doc/Milestone_3.md) and [app](https://panntingg.shinyapps.io/mental_health_app_3_0/) that has reflected on your suggestion.
