### ISSUE TITLE
Milestone3_Feedback

### ISSUE THREAD

**Issue by everittB** [UBC-MDS/DSCI_532_Mental-health-survey-Tech#16]
- I like the filter selection tab  
- At first look, the plots are not super intuitive as to what they are exactly showing 
- Can you make the plots scroll within a fixed 'section' so the entire page doesn't scroll. You lose the filter options when you scroll down to see the rest of the plots.

**Comment by sabrinatkk** [comment]
Thank you for your recommendation, @everittB !

Please review our [milestone 3 writeup](https://github.com/UBC-MDS/DSCI_532_Mental-health-survey-Tech/blob/master/doc/Milestone_3.md) and [app](https://panntingg.shinyapps.io/mental_health_app_3_0/) that has reflected on your suggestion.
