### ISSUE TITLE
Milestone 2 TA feedback

### ISSUE THREAD

**Issue by aleurcelay** [UBC-MDS/DSCI_532_Mental-health-survey-Tech#18]
* Organized repo, the link to app is easy to find :). 
* You didn't include a code of conduct.
* The app has too many plots, you can probably use facet wrap to display them in a 2x2 instead of scrolling so much. You might want to consider a selection of variables to limit the number of plots displayed at once.
* Increase the size of the axis and label x axis.
* I recommend including a dropdown menu for country selection or a text widget to select multiple countries at once instead of the radio buttons.
* Maybe change the gender selection to checkboxes to allow seeing trends for all genders.
* Your code has minimal comments, try to add some more.
* The new lines between code lines are unnecessary and makes the code really hard to read.

**Comment by sabrinatkk** [comment]
@aleurcelay  Thank you for your recommendation. 

Please review our ![milestone 3 writeup](https://github.com/UBC-MDS/DSCI_532_Mental-health-survey-Tech/blob/master/doc/Milestone_3.md)
